/*7. Escreva um script que leia o nome dos 26 estados brasileiros e do distrito federal e os armazene em um array, ao final deve-se 
imprimir o array com os valores ordenados em ordem alfabética.*/
let estados = [
    'Acre',
    'Alagoas',
    'Amapá',
    'Amazonas',
    'Bahia',
    'Ceará',
    'Distrito Federal',
    'Espírito Santo',
    'Goiás',
    'Maranhão',
    'Mato Grosso',
    'Mato Grosso do Sul',
    'Minas Gerais',
    'Pará',
    'Paraíba',
    'Paraná',
    'Pernambuco',
    'Piauí',
    'Rio de Janeiro',
    'Rio Grande do Norte',
    'Rio Grande do Sul',
    'Rondônia',
    'Roraima',
    'Santa Catarina',
    'São Paulo',
    'Sergipe',
    'Tocantins',
    ]
for(let k=0;k<=26;k++){
    document.write(estados[k]+ "<br>")
    
}
